#
# Copied verbatim from Tide and then slightly modified. Great work everyone!
#
# https://github.com/http-rs/tide/blob/main/.github/workflows/ci.yaml
#
name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build_and_test:
    name: build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]

    steps:
      - uses: actions/checkout@master

      - name: Install ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --bins --examples --features __test

      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --package via --features __test

      - name: test pubsub
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --package via-pubsub --features __test

      - name: test router
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --package via-router

  test_examples:
    name: test examples
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: via_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d via_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:8
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/via_test
      REDIS_URL: redis://localhost:6379

    steps:
      - uses: actions/checkout@master

      - name: Install stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install diesel-cli
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --locked diesel_cli --no-default-features --features postgres

      - name: Run migrations
        run: diesel migration run --migration-dir ./examples/chat/migrations

      - name: test examples
        uses: actions-rs/cargo@v1
        with:
          working-directory: ./examples
          command: test
          args: --examples --features __test

  fmt_clippy_and_docs:
    name: fmt, clippy, and docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features __test --tests --examples -- -D warnings

      - name: fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps
